//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpiredPlanUserMailLog
    {
        public int Id { get; set; }
        public decimal UserID { get; set; }
        public string ReminderType { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public string ReminderStatus { get; set; }
        public Nullable<System.DateTime> NextReminderDueDate { get; set; }
        public Nullable<System.DateTime> RecordOperationDate { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
