//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailLog
    {
        public int Id { get; set; }
        public decimal UserID { get; set; }
        public Nullable<System.DateTime> ReminderOne { get; set; }
        public Nullable<System.DateTime> ReminderTwo { get; set; }
        public Nullable<System.DateTime> ReminderThree { get; set; }
        public Nullable<System.DateTime> ReminderFour { get; set; }
        public Nullable<System.DateTime> ReminderFive { get; set; }
        public Nullable<System.DateTime> ReminderSix { get; set; }
        public string LastReminderStatus { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
