//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaypalResponse
    {
        public int Id { get; set; }
        public decimal user_id { get; set; }
        public string Paypal_ReferenceId { get; set; }
        public string intent { get; set; }
        public string payer { get; set; }
        public string application_context { get; set; }
        public string response_state { get; set; }
        public string experience_profile_id { get; set; }
        public string note_to_payer { get; set; }
        public string failure_reason { get; set; }
        public string create_time { get; set; }
        public string update_time { get; set; }
        public string links { get; set; }
        public string payee { get; set; }
    
        public virtual User_Profile User_Profile { get; set; }
    }
}
