//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_page_map
    {
        public decimal id { get; set; }
        public decimal role_id { get; set; }
        public decimal page_id { get; set; }
        public string status { get; set; }
    
        public virtual page_master page_master { get; set; }
        public virtual Role_Master Role_Master { get; set; }
    }
}
