//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rule2_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rule2_Master()
        {
            this.StateActivity__with_Rule2 = new HashSet<StateActivity__with_Rule2>();
        }
    
        public decimal Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Unit { get; set; }
        public Nullable<decimal> Hours { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateActivity__with_Rule2> StateActivity__with_Rule2 { get; set; }
    }
}
