//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public State_Master()
        {
            this.State_Rule3_Marriage = new HashSet<State_Rule3_Marriage>();
            this.State_Activity_Mapping = new HashSet<State_Activity_Mapping>();
            this.State_Category_With_Rule4_Mapping = new HashSet<State_Category_With_Rule4_Mapping>();
            this.User_Training_Transaction = new HashSet<User_Training_Transaction>();
            this.StateActivity__with_Rule2 = new HashSet<StateActivity__with_Rule2>();
            this.StateActivitySubActivityWithRule1 = new HashSet<StateActivitySubActivityWithRule1>();
            this.Sub_Activity_Master = new HashSet<Sub_Activity_Master>();
            this.Total_Unit_Master = new HashSet<Total_Unit_Master>();
            this.User_Profile = new HashSet<User_Profile>();
            this.User_Profile1 = new HashSet<User_Profile>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public decimal Country_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State_Rule3_Marriage> State_Rule3_Marriage { get; set; }
        public virtual Country_Master Country_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State_Activity_Mapping> State_Activity_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State_Category_With_Rule4_Mapping> State_Category_With_Rule4_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Transaction> User_Training_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateActivity__with_Rule2> StateActivity__with_Rule2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateActivitySubActivityWithRule1> StateActivitySubActivityWithRule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sub_Activity_Master> Sub_Activity_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Total_Unit_Master> Total_Unit_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Profile> User_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Profile> User_Profile1 { get; set; }
    }
}
