//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_Category_With_Rule4_Mapping
    {
        public decimal Id { get; set; }
        public decimal StateID { get; set; }
        public decimal CategoryID { get; set; }
        public decimal Rule4_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
    
        public virtual Category_Master Category_Master { get; set; }
        public virtual Rule4_Master Rule4_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
