//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_Rule3_Marriage
    {
        public decimal ID { get; set; }
        public decimal StateID { get; set; }
        public decimal Rule3_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
    
        public virtual Rule3_Master Rule3_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
