//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateActivity__with_Rule2
    {
        public decimal Id { get; set; }
        public decimal StateID { get; set; }
        public decimal ActivityID { get; set; }
        public decimal Rule2_ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Status { get; set; }
    
        public virtual Activity_Master Activity_Master { get; set; }
        public virtual Rule2_Master Rule2_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
