//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class State_Activity_Mapping
    {
        public int Id { get; set; }
        public decimal StateID { get; set; }
        public decimal ActivityID { get; set; }
    
        public virtual Activity_Master Activity_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
    }
}
