//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sub_Activity_Master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sub_Activity_Master()
        {
            this.StateActivitySubActivityWithRule1 = new HashSet<StateActivitySubActivityWithRule1>();
            this.User_Training_Transaction = new HashSet<User_Training_Transaction>();
            this.User_Training_Status = new HashSet<User_Training_Status>();
        }
    
        public decimal ID { get; set; }
        public string Name { get; set; }
        public decimal Activity_ID { get; set; }
        public string ShortName { get; set; }
        public decimal StateID { get; set; }
    
        public virtual Activity_Master Activity_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StateActivitySubActivityWithRule1> StateActivitySubActivityWithRule1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Transaction> User_Training_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Status> User_Training_Status { get; set; }
    }
}
