//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Transaction_Master
    {
        public decimal Id { get; set; }
        public decimal Rate_ID { get; set; }
        public decimal User_ID { get; set; }
        public Nullable<decimal> PlanID { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public string Payment_Status { get; set; }
        public string Transection_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Payment_Date { get; set; }
        public Nullable<int> Invoice_No { get; set; }
        public string Payment_Method { get; set; }
        public string Paypal_PayerId { get; set; }
        public string Transaction_Status { get; set; }
    
        public virtual Plan_Master Plan_Master { get; set; }
        public virtual Rate_Card Rate_Card { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
