//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Subscription
    {
        public decimal ID { get; set; }
        public Nullable<decimal> UserID { get; set; }
        public Nullable<decimal> PlanID { get; set; }
        public Nullable<decimal> RateID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string PaymentStatus { get; set; }
        public string TransectionID { get; set; }
        public string Status { get; set; }
    
        public virtual Plan_Master Plan_Master { get; set; }
        public virtual Rate_Card Rate_Card { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
