//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Role_Mapping
    {
        public decimal Id { get; set; }
        public decimal user_ID { get; set; }
        public decimal role_id { get; set; }
        public string login_id { get; set; }
        public string password { get; set; }
        public string confirm_password { get; set; }
        public string description { get; set; }
        public string status { get; set; }
    
        public virtual Role_Master Role_Master { get; set; }
        public virtual User_Profile User_Profile { get; set; }
    }
}
