//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Training_Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Training_Transaction()
        {
            this.User_Training_Status = new HashSet<User_Training_Status>();
        }
    
        public decimal Id { get; set; }
        public decimal User_Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> State_Id { get; set; }
        public Nullable<decimal> Category_Id { get; set; }
        public Nullable<decimal> Activity_Id { get; set; }
        public Nullable<decimal> SubActivity_Id { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Provider { get; set; }
        public string Financial_Year { get; set; }
        public string Your_Role { get; set; }
        public string Forwardable { get; set; }
        public string Has_been_Forwarded { get; set; }
        public string Descrption { get; set; }
        public byte[] UploadedFile { get; set; }
        public string UploadedFileName { get; set; }
    
        public virtual Activity_Master Activity_Master { get; set; }
        public virtual Category_Master Category_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
        public virtual Sub_Activity_Master Sub_Activity_Master { get; set; }
        public virtual User_Profile User_Profile { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Status> User_Training_Status { get; set; }
    }
}
