//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lexnarro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User_Profile()
        {
            this.ExpiredPlanUserMailLogs = new HashSet<ExpiredPlanUserMailLog>();
            this.MailLogs = new HashSet<MailLog>();
            this.User_Training_Transaction = new HashSet<User_Training_Transaction>();
            this.User_Training_Status = new HashSet<User_Training_Status>();
            this.User_Role_Mapping = new HashSet<User_Role_Mapping>();
            this.User_Subscription = new HashSet<User_Subscription>();
            this.PaypalResponses = new HashSet<PaypalResponse>();
            this.User_Transaction_Master = new HashSet<User_Transaction_Master>();
        }
    
        public decimal ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string OtherName { get; set; }
        public string StreetNumber { get; set; }
        public string StreetName { get; set; }
        public Nullable<decimal> PostCode { get; set; }
        public string Suburb { get; set; }
        public Nullable<decimal> StateID { get; set; }
        public Nullable<decimal> CountryID { get; set; }
        public Nullable<decimal> StateEnrolled { get; set; }
        public Nullable<decimal> LawSocietyNumber { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public decimal Role_id { get; set; }
        public string Address { get; set; }
        public string Device_Imei { get; set; }
        public string Device_Token { get; set; }
        public string Device_Type { get; set; }
        public string IsDeleted { get; set; }
        public string AccountConfirmed { get; set; }
        public Nullable<System.Guid> ActivationCode { get; set; }
        public string MailUnsubscribed { get; set; }
        public string Firm { get; set; }
        public string Current_Financial_year { get; set; }
    
        public virtual Country_Master Country_Master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExpiredPlanUserMailLog> ExpiredPlanUserMailLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailLog> MailLogs { get; set; }
        public virtual Role_Master Role_Master { get; set; }
        public virtual State_Master State_Master { get; set; }
        public virtual State_Master State_Master1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Transaction> User_Training_Transaction { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Training_Status> User_Training_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Role_Mapping> User_Role_Mapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Subscription> User_Subscription { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaypalResponse> PaypalResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Transaction_Master> User_Transaction_Master { get; set; }
    }
}
